oit:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: graduation_project
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tHbYBjrbBZpi9jBegwv
    access-key-secret: GORCmFtdwbUsYSlscAemHgpWdTQcR6
    bucket-name: graduation-projectss
  redis:
    host: localhost
    port: 6379