oit:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: graduation_project
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tHbYBjrbBZpi9jBegwv
    access-key-secret: GORCmFtdwbUsYSlscAemHgpWdTQcR6
    bucket-name: graduation-projectss
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: wxc9cbafa431b8fc20
    secret: ef26e3bd1698d6a917143300092e23a7
    mchid: # 1561414331
    mchSerialNo: # 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: # D:\apiclient_key.pem
    apiV3Key: # CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: # D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: # https://www.weixin.qq.com/notify/paySuccess
    refundNotifyUrl: # https://www.weixin.qq.com/notify/refundSuccess